name: Build Development
on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Standard Build
        run: npm run build
      - name: Prod Build
        run: npm run build:prod
